import type { Locale } from "./translations";

type Section = { title: string; body: string };
type LegalLocale = {
  privacy: { title: string; description: string; updated: string; sections: Section[] };
  terms: { title: string; description: string; updated: string; sections: Section[] };
  feedback: { title: string; description: string; intro: string; name: string; email: string; category: string; message: string; send: string; unavailable: string; note: string; categories: string[] };
  nav: { privacy: string; terms: string; feedback: string; back: string };
};

const updated = "August 18, 2026";

export const legalCopy: Record<Locale, LegalLocale> = {
  en:{
    privacy:{title:"Privacy Policy",description:"How White Screen handles data, local preferences, downloads, and feedback.",updated:`Last updated: ${updated}`,sections:[
      {title:"Information we collect",body:"White Screen does not require an account and does not intentionally collect personal information while you use the color-screen tool."},
      {title:"Local preferences",body:"Your light, dark, or system theme preference is stored in your browser using localStorage. It stays on your device and can be cleared through your browser settings."},
      {title:"Image generation",body:"Downloaded PNG images are generated locally in your browser. The selected color and resolution are not uploaded to our servers."},
      {title:"Hosting and technical logs",body:"A future hosting provider may process standard technical logs such as IP address, browser type, requested URL, and time of access for security and reliable delivery."},
      {title:"Feedback",body:"If you choose to send feedback by email, we may receive your email address, name, message, and any information you voluntarily include. We use it only to respond and improve the service."},
      {title:"Cookies and third parties",body:"The current application does not use advertising cookies or analytics. If those services are added later, this policy and any required consent controls will be updated first."},
      {title:"Children and changes",body:"The service is not designed to collect children’s personal data. This policy may change as the project evolves; the revision date will always appear on this page."},
    ]},
    terms:{title:"Terms & Conditions",description:"Rules and conditions for using the free White Screen web application.",updated:`Last updated: ${updated}`,sections:[
      {title:"Acceptance",body:"By using White Screen, you agree to these terms. If you do not agree, please stop using the application."},
      {title:"The service",body:"White Screen provides free color displays, fullscreen tools, resolution controls, and locally generated image downloads. Features may change during development."},
      {title:"Permitted use",body:"You may use the tool for personal, educational, creative, and commercial display-testing purposes. Do not misuse it to disrupt systems, violate laws, or infringe other people’s rights."},
      {title:"Intellectual property",body:"The application interface and original written content are protected by applicable intellectual-property laws. Images you generate from plain colors may be used without restriction from us."},
      {title:"Availability and warranties",body:"The service is provided “as is” without guarantees of uninterrupted availability, exact color calibration, diagnostic accuracy, or suitability for a particular purpose."},
      {title:"Limitation of liability",body:"To the extent allowed by law, we are not responsible for display damage, data loss, eye discomfort, or indirect losses resulting from use of the service. Use appropriate brightness and take breaks."},
      {title:"Updates",body:"We may update the application and these terms. Continued use after an update means you accept the revised terms."},
    ]},
    feedback:{title:"Feedback & Contact",description:"Send a bug report, feature idea, translation correction, or other feedback about White Screen.",intro:"Your feedback helps improve the tool. Use this page for bugs, feature ideas, translation corrections, accessibility issues, or general questions.",name:"Name (optional)",email:"Email (optional)",category:"Type of feedback",message:"Message",send:"Open email to send",unavailable:"The feedback email will be enabled before launch.",note:"Submitting opens your email application. Nothing is sent until you review and send the email yourself.",categories:["Bug report","Feature request","Translation","Accessibility","General feedback"]},
    nav:{privacy:"Privacy Policy",terms:"Terms & Conditions",feedback:"Feedback & Contact",back:"Back to White Screen"},
  },
  es:{
    privacy:{title:"Política de privacidad",description:"Cómo White Screen trata los datos, preferencias locales, descargas y comentarios.",updated:"Última actualización: 18 de agosto de 2026",sections:[
      {title:"Información que recopilamos",body:"White Screen no requiere una cuenta y no recopila intencionalmente información personal mientras utilizas la herramienta de colores."},{title:"Preferencias locales",body:"La preferencia de tema claro, oscuro o del sistema se guarda en tu navegador mediante localStorage. Permanece en tu dispositivo y puedes eliminarla desde el navegador."},{title:"Generación de imágenes",body:"Los PNG se generan localmente en el navegador. El color y la resolución seleccionados no se suben a nuestros servidores."},{title:"Hosting y registros técnicos",body:"El futuro proveedor de alojamiento podría procesar registros técnicos estándar como dirección IP, navegador, URL solicitada y hora de acceso para seguridad y funcionamiento."},{title:"Feedback",body:"Si decides escribirnos por correo, podremos recibir tu dirección, nombre, mensaje y cualquier dato que incluyas voluntariamente. Se utilizará para responder y mejorar el servicio."},{title:"Cookies y terceros",body:"La aplicación actual no utiliza cookies publicitarias ni analítica. Si se añaden estos servicios, actualizaremos primero esta política y los controles de consentimiento necesarios."},{title:"Menores y cambios",body:"El servicio no está diseñado para recopilar datos personales de menores. Esta política podrá cambiar durante el desarrollo y mostrará siempre su fecha de revisión."},
    ]},
    terms:{title:"Términos y condiciones",description:"Condiciones para utilizar gratuitamente la aplicación White Screen.",updated:"Última actualización: 18 de agosto de 2026",sections:[
      {title:"Aceptación",body:"Al utilizar White Screen aceptas estas condiciones. Si no estás de acuerdo, deja de utilizar la aplicación."},{title:"El servicio",body:"White Screen proporciona pantallas de colores, modo completo, controles de resolución y descargas generadas localmente. Las funciones pueden cambiar durante el desarrollo."},{title:"Uso permitido",body:"Puedes utilizar la herramienta con fines personales, educativos, creativos y comerciales de prueba. No debes usarla para infringir leyes, derechos o interrumpir sistemas."},{title:"Propiedad intelectual",body:"La interfaz y el contenido escrito original están protegidos por las leyes aplicables. Las imágenes de colores planos que generes pueden utilizarse sin restricciones por nuestra parte."},{title:"Disponibilidad y garantías",body:"El servicio se proporciona “tal cual”, sin garantizar disponibilidad continua, calibración exacta, precisión diagnóstica o idoneidad para un propósito concreto."},{title:"Limitación de responsabilidad",body:"En la medida permitida por la ley, no respondemos por daños de pantalla, pérdida de datos, molestias visuales o pérdidas indirectas. Utiliza un brillo adecuado y realiza descansos."},{title:"Actualizaciones",body:"Podemos actualizar la aplicación y estas condiciones. El uso continuado después de una actualización implica aceptar la versión revisada."},
    ]},
    feedback:{title:"Feedback y contacto",description:"Envía errores, ideas, correcciones de traducción o comentarios sobre White Screen.",intro:"Tus comentarios ayudan a mejorar la herramienta. Utiliza esta página para errores, nuevas funciones, traducciones, accesibilidad o preguntas generales.",name:"Nombre (opcional)",email:"Correo (opcional)",category:"Tipo de comentario",message:"Mensaje",send:"Abrir correo para enviar",unavailable:"El correo de feedback se habilitará antes del lanzamiento.",note:"El formulario abre tu aplicación de correo. Nada se envía hasta que revises y envíes el mensaje.",categories:["Reportar un error","Solicitar una función","Traducción","Accesibilidad","Comentario general"]},
    nav:{privacy:"Política de privacidad",terms:"Términos y condiciones",feedback:"Feedback y contacto",back:"Volver a White Screen"},
  },
  de:{
    privacy:{title:"Datenschutzerklärung",description:"Umgang mit Daten, lokalen Einstellungen, Downloads und Feedback.",updated:"Zuletzt aktualisiert: 18. August 2026",sections:[{title:"Erhobene Informationen",body:"White Screen erfordert kein Konto und erhebt bei der Nutzung des Farbwerkzeugs nicht absichtlich personenbezogene Daten."},{title:"Lokale Einstellungen",body:"Die Themenauswahl wird per localStorage auf Ihrem Gerät gespeichert und kann im Browser gelöscht werden."},{title:"Bilderstellung",body:"PNG-Dateien werden lokal im Browser erzeugt; Farbe und Auflösung werden nicht hochgeladen."},{title:"Hosting-Protokolle",body:"Ein künftiger Hosting-Anbieter kann technische Daten wie IP-Adresse, Browser, URL und Zugriffszeit für Sicherheit und Betrieb verarbeiten."},{title:"Feedback",body:"Bei einer freiwilligen E-Mail können Name, Adresse, Nachricht und weitere angegebene Daten verarbeitet werden, um zu antworten und den Dienst zu verbessern."},{title:"Cookies und Dritte",body:"Derzeit werden keine Werbe-Cookies oder Analysedienste verwendet. Änderungen werden vor ihrer Einführung in dieser Erklärung beschrieben."},{title:"Kinder und Änderungen",body:"Der Dienst ist nicht für die Erhebung von Kinderdaten ausgelegt. Änderungen werden mit einem neuen Datum veröffentlicht."}]},
    terms:{title:"Allgemeine Bedingungen",description:"Bedingungen für die kostenlose Nutzung von White Screen.",updated:"Zuletzt aktualisiert: 18. August 2026",sections:[{title:"Zustimmung",body:"Mit der Nutzung stimmen Sie diesen Bedingungen zu."},{title:"Dienst",body:"White Screen bietet Farbflächen, Vollbild, Auflösungen und lokale Bilddownloads. Funktionen können sich während der Entwicklung ändern."},{title:"Zulässige Nutzung",body:"Persönliche, schulische, kreative und kommerzielle Displaytests sind erlaubt. Rechtswidrige oder schädliche Nutzung ist untersagt."},{title:"Urheberrecht",body:"Oberfläche und Originaltexte sind geschützt. Selbst erzeugte einfarbige Bilder dürfen ohne Einschränkung durch uns genutzt werden."},{title:"Gewährleistung",body:"Der Dienst wird ohne Garantie für Verfügbarkeit, Kalibrierung oder Diagnosegenauigkeit bereitgestellt."},{title:"Haftung",body:"Soweit gesetzlich zulässig, haften wir nicht für Display- oder Datenverlust, Augenbeschwerden oder indirekte Schäden. Verwenden Sie angemessene Helligkeit."},{title:"Aktualisierungen",body:"Dienst und Bedingungen können aktualisiert werden. Weitere Nutzung gilt als Annahme."}]},
    feedback:{title:"Feedback & Kontakt",description:"Fehler, Ideen, Übersetzungskorrekturen oder Feedback senden.",intro:"Helfen Sie uns mit Fehlerberichten, Funktionsideen, Übersetzungen, Barrierefreiheit oder Fragen.",name:"Name (optional)",email:"E-Mail (optional)",category:"Art des Feedbacks",message:"Nachricht",send:"E-Mail öffnen",unavailable:"Die Feedback-Adresse wird vor dem Start aktiviert.",note:"Das Formular öffnet Ihr E-Mail-Programm. Gesendet wird erst nach Ihrer Bestätigung.",categories:["Fehlerbericht","Funktionswunsch","Übersetzung","Barrierefreiheit","Allgemeines Feedback"]},nav:{privacy:"Datenschutz",terms:"Bedingungen",feedback:"Feedback & Kontakt",back:"Zurück zu White Screen"},
  },
  pt:{
    privacy:{title:"Política de Privacidade",description:"Como tratamos dados, preferências locais, downloads e feedback.",updated:"Última atualização: 18 de agosto de 2026",sections:[{title:"Informações coletadas",body:"White Screen não exige conta nem coleta intencionalmente dados pessoais durante o uso da ferramenta."},{title:"Preferências locais",body:"O tema é salvo no seu dispositivo pelo localStorage e pode ser apagado nas configurações do navegador."},{title:"Geração de imagens",body:"Os PNGs são criados localmente; cor e resolução não são enviados ao servidor."},{title:"Registros de hospedagem",body:"O futuro provedor poderá tratar IP, navegador, URL e horário para segurança e funcionamento."},{title:"Feedback",body:"Ao enviar e-mail, poderemos receber nome, endereço, mensagem e dados fornecidos voluntariamente para responder e melhorar o serviço."},{title:"Cookies e terceiros",body:"Atualmente não usamos publicidade ou análise. Esta política e os controles de consentimento serão atualizados antes de qualquer mudança."},{title:"Crianças e alterações",body:"O serviço não foi criado para coletar dados de crianças. Alterações serão publicadas com nova data."}]},
    terms:{title:"Termos e Condições",description:"Condições de uso gratuito do White Screen.",updated:"Última atualização: 18 de agosto de 2026",sections:[{title:"Aceitação",body:"Ao usar o White Screen, você aceita estes termos."},{title:"Serviço",body:"Oferecemos telas coloridas, modo completo, resoluções e downloads locais. Os recursos podem mudar durante o desenvolvimento."},{title:"Uso permitido",body:"São permitidos usos pessoais, educacionais, criativos e comerciais de teste. Uso ilegal ou prejudicial é proibido."},{title:"Propriedade intelectual",body:"A interface e os textos originais são protegidos. Imagens de cores simples geradas por você podem ser usadas livremente."},{title:"Garantias",body:"O serviço é fornecido no estado atual, sem garantia de disponibilidade, calibração ou precisão diagnóstica."},{title:"Responsabilidade",body:"Quando permitido por lei, não respondemos por danos ao monitor, perda de dados, desconforto visual ou perdas indiretas."},{title:"Atualizações",body:"Podemos atualizar o serviço e estes termos; o uso posterior representa aceitação."}]},
    feedback:{title:"Feedback e contato",description:"Envie erros, ideias, correções ou comentários.",intro:"Ajude a melhorar a ferramenta com erros, recursos, traduções, acessibilidade ou dúvidas.",name:"Nome (opcional)",email:"E-mail (opcional)",category:"Tipo de feedback",message:"Mensagem",send:"Abrir e-mail",unavailable:"O e-mail será ativado antes do lançamento.",note:"O formulário abre seu aplicativo de e-mail e nada é enviado sem sua confirmação.",categories:["Erro","Novo recurso","Tradução","Acessibilidade","Comentário geral"]},nav:{privacy:"Privacidade",terms:"Termos",feedback:"Feedback e contato",back:"Voltar ao White Screen"},
  },
  fr:{
    privacy:{title:"Politique de confidentialité",description:"Traitement des données, préférences locales, téléchargements et retours.",updated:"Dernière mise à jour : 18 août 2026",sections:[{title:"Données collectées",body:"White Screen ne demande pas de compte et ne collecte pas intentionnellement de données personnelles pendant l’utilisation."},{title:"Préférences locales",body:"Le thème est enregistré sur votre appareil avec localStorage et peut être supprimé dans le navigateur."},{title:"Création d’images",body:"Les PNG sont générés localement ; couleur et résolution ne sont pas envoyées à nos serveurs."},{title:"Journaux d’hébergement",body:"Un futur hébergeur pourra traiter IP, navigateur, URL et heure d’accès pour la sécurité et la fiabilité."},{title:"Retours",body:"Un e-mail volontaire peut nous transmettre nom, adresse, message et autres données afin de répondre et améliorer le service."},{title:"Cookies et tiers",body:"Aucune publicité ni analyse n’est utilisée actuellement. La politique et les contrôles seront mis à jour avant tout ajout."},{title:"Enfants et modifications",body:"Le service n’est pas conçu pour recueillir les données des enfants. Toute modification affichera une nouvelle date."}]},
    terms:{title:"Conditions générales",description:"Conditions d’utilisation gratuite de White Screen.",updated:"Dernière mise à jour : 18 août 2026",sections:[{title:"Acceptation",body:"En utilisant White Screen, vous acceptez ces conditions."},{title:"Service",body:"Le service fournit couleurs, plein écran, résolutions et téléchargements locaux. Les fonctions peuvent évoluer."},{title:"Usage autorisé",body:"Les usages personnels, éducatifs, créatifs et commerciaux de test sont autorisés. Tout usage illégal ou nuisible est interdit."},{title:"Propriété intellectuelle",body:"L’interface et les textes originaux sont protégés. Les images unies que vous générez peuvent être utilisées librement."},{title:"Garanties",body:"Le service est fourni en l’état sans garantie de disponibilité, calibration ou précision diagnostique."},{title:"Responsabilité",body:"Dans les limites légales, nous ne répondons pas des dommages d’écran, pertes de données, gêne visuelle ou dommages indirects."},{title:"Mises à jour",body:"Le service et ces conditions peuvent évoluer ; la poursuite de l’utilisation vaut acceptation."}]},
    feedback:{title:"Retours et contact",description:"Envoyez un bug, une idée, une correction ou un commentaire.",intro:"Aidez-nous avec les bugs, idées, traductions, problèmes d’accessibilité ou questions.",name:"Nom (facultatif)",email:"E-mail (facultatif)",category:"Type de retour",message:"Message",send:"Ouvrir l’e-mail",unavailable:"L’adresse sera activée avant le lancement.",note:"Le formulaire ouvre votre messagerie. Rien n’est envoyé avant votre confirmation.",categories:["Bug","Fonctionnalité","Traduction","Accessibilité","Commentaire général"]},nav:{privacy:"Confidentialité",terms:"Conditions",feedback:"Retours et contact",back:"Retour à White Screen"},
  },
  it:{
    privacy:{title:"Informativa sulla privacy",description:"Gestione di dati, preferenze locali, download e feedback.",updated:"Ultimo aggiornamento: 18 agosto 2026",sections:[{title:"Dati raccolti",body:"White Screen non richiede account e non raccoglie intenzionalmente dati personali durante l’uso."},{title:"Preferenze locali",body:"Il tema viene salvato sul dispositivo con localStorage e può essere cancellato dal browser."},{title:"Creazione delle immagini",body:"I PNG sono generati localmente; colore e risoluzione non vengono caricati sui server."},{title:"Registri di hosting",body:"Un futuro provider può trattare IP, browser, URL e orario per sicurezza e affidabilità."},{title:"Feedback",body:"Un’e-mail volontaria può comunicarci nome, indirizzo, messaggio e altri dati per rispondere e migliorare il servizio."},{title:"Cookie e terze parti",body:"Attualmente non usiamo pubblicità o analisi. Informativa e consenso saranno aggiornati prima di aggiungerli."},{title:"Minori e modifiche",body:"Il servizio non è progettato per raccogliere dati di minori. Le modifiche mostreranno una nuova data."}]},
    terms:{title:"Termini e condizioni",description:"Condizioni per utilizzare gratuitamente White Screen.",updated:"Ultimo aggiornamento: 18 agosto 2026",sections:[{title:"Accettazione",body:"Utilizzando White Screen accetti questi termini."},{title:"Servizio",body:"Offriamo colori, schermo intero, risoluzioni e download locali. Le funzioni possono cambiare durante lo sviluppo."},{title:"Uso consentito",body:"Sono consentiti usi personali, didattici, creativi e commerciali di test. Sono vietati usi illegali o dannosi."},{title:"Proprietà intellettuale",body:"Interfaccia e testi originali sono protetti. Le immagini a tinta unita generate possono essere usate liberamente."},{title:"Garanzie",body:"Il servizio è fornito così com’è, senza garanzie di disponibilità, calibrazione o precisione diagnostica."},{title:"Responsabilità",body:"Nei limiti di legge non rispondiamo di danni allo schermo, perdita di dati, disagio visivo o perdite indirette."},{title:"Aggiornamenti",body:"Servizio e termini possono cambiare; l’uso successivo implica accettazione."}]},
    feedback:{title:"Feedback e contatti",description:"Invia errori, idee, correzioni o commenti.",intro:"Aiutaci con bug, funzioni, traduzioni, accessibilità o domande.",name:"Nome (facoltativo)",email:"E-mail (facoltativa)",category:"Tipo di feedback",message:"Messaggio",send:"Apri e-mail",unavailable:"L’indirizzo sarà attivato prima del lancio.",note:"Il modulo apre il programma e-mail. Nulla viene inviato senza conferma.",categories:["Errore","Nuova funzione","Traduzione","Accessibilità","Commento generale"]},nav:{privacy:"Privacy",terms:"Termini",feedback:"Feedback e contatti",back:"Torna a White Screen"},
  },
  nl:{
    privacy:{title:"Privacybeleid",description:"Hoe we omgaan met gegevens, lokale voorkeuren, downloads en feedback.",updated:"Laatst bijgewerkt: 18 augustus 2026",sections:[{title:"Verzamelde informatie",body:"White Screen vereist geen account en verzamelt niet bewust persoonsgegevens tijdens het gebruik."},{title:"Lokale voorkeuren",body:"De themakeuze wordt met localStorage op je apparaat opgeslagen en kan in de browser worden verwijderd."},{title:"Afbeeldingen",body:"PNG’s worden lokaal gemaakt; kleur en resolutie worden niet naar servers verzonden."},{title:"Hostinglogs",body:"Een toekomstige host kan IP, browser, URL en tijd verwerken voor veiligheid en betrouwbare levering."},{title:"Feedback",body:"Een vrijwillige e-mail kan naam, adres, bericht en andere gegevens bevatten om te antwoorden en de dienst te verbeteren."},{title:"Cookies en derden",body:"Momenteel gebruiken we geen advertenties of analytics. Beleid en toestemming worden bijgewerkt voordat dit verandert."},{title:"Kinderen en wijzigingen",body:"De dienst is niet bedoeld om kindergegevens te verzamelen. Wijzigingen krijgen een nieuwe datum."}]},
    terms:{title:"Algemene voorwaarden",description:"Voorwaarden voor gratis gebruik van White Screen.",updated:"Laatst bijgewerkt: 18 augustus 2026",sections:[{title:"Aanvaarding",body:"Door White Screen te gebruiken ga je akkoord met deze voorwaarden."},{title:"Dienst",body:"We bieden kleurvlakken, volledig scherm, resoluties en lokale downloads. Functies kunnen tijdens ontwikkeling veranderen."},{title:"Toegestaan gebruik",body:"Persoonlijke, educatieve, creatieve en commerciële schermtests zijn toegestaan. Illegaal of schadelijk gebruik niet."},{title:"Intellectueel eigendom",body:"Interface en originele teksten zijn beschermd. Zelfgemaakte effen afbeeldingen mag je vrij gebruiken."},{title:"Garanties",body:"De dienst wordt geleverd zoals hij is, zonder garantie op beschikbaarheid, kalibratie of diagnostische nauwkeurigheid."},{title:"Aansprakelijkheid",body:"Voor zover wettelijk toegestaan zijn we niet aansprakelijk voor schermschade, gegevensverlies, oogklachten of indirect verlies."},{title:"Updates",body:"Dienst en voorwaarden kunnen wijzigen; verder gebruik geldt als aanvaarding."}]},
    feedback:{title:"Feedback en contact",description:"Stuur fouten, ideeën, correcties of andere feedback.",intro:"Help met bugs, functies, vertalingen, toegankelijkheid of vragen.",name:"Naam (optioneel)",email:"E-mail (optioneel)",category:"Soort feedback",message:"Bericht",send:"E-mail openen",unavailable:"Het feedbackadres wordt voor de lancering geactiveerd.",note:"Het formulier opent je e-mailprogramma. Er wordt niets verstuurd zonder bevestiging.",categories:["Foutmelding","Functieverzoek","Vertaling","Toegankelijkheid","Algemene feedback"]},nav:{privacy:"Privacy",terms:"Voorwaarden",feedback:"Feedback en contact",back:"Terug naar White Screen"},
  },
};

export type LegalPageKey = "privacy" | "terms" | "feedback";
export function legalPath(locale: Locale, page: LegalPageKey) {
  const slug = page === "privacy" ? "privacy-policy" : page === "terms" ? "terms-and-conditions" : "feedback";
  return `${locale === "en" ? "" : `/${locale}`}/${slug}/`;
}
